[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tyru/eskk.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-brightest'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'thinca/vim-fontzoom'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'MaxSt/FlatColor'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'mattn/benchvimrc-vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo = 'tommcdo/vim-lion'

[[plugins]]
repo = 'cocopon/vaffle.vim'
#on_cmd = ['Vaffle']

[[plugins]]
repo = 'mattn/vimtweak'
if   = '''has('win32') && ! has('kaoriya')'''

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'thomd/vim-wasabi-colorscheme'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'fszymanski/deoplete-emoji'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'iyuuya/denite-ale'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'mopp/sky-color-clock.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'hisaknown/nanomap.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'hisaknown/deoplete-latex'

[[plugins]]
repo = 'sts10/vim-pink-moon'

[[plugins]]
repo = 'Heorhiy/VisualStudioDark.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'hisaknown/jupyterkernel.vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# 
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'
