[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-brightest'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'thinca/vim-fontzoom'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'MaxSt/FlatColor'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tommcdo/vim-lion'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'mattn/vimtweak'
if   = '''has('win32') && ! has('kaoriya')'''

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'thomd/vim-wasabi-colorscheme'

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'hisaknown/nanomap.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'sts10/vim-pink-moon'

[[plugins]]
repo = 'Heorhiy/VisualStudioDark.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'hisaknown/jupyterkernel.vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# 
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-cmdline'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'
