[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
on_cmd = ['PrevimOpen']

[[plugins]]
repo = 'thinca/vim-showtime'
on_ft = ['markdown']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'syngan/vim-pukiwiki'
on_cmd = ['PukiWiki']
on_ft = ['pukiwiki']

[[plugins]]
repo = 'rhysd/vim-grammarous'
on_cmd = ['GrammarousCheck']

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs']

[[plugins]]
repo = 'rhysd/vim-notes-cli'
on_cmd = ['Notes', 'NotesSelect', 'NotesNew', 'NotesList', 'NotesGrep']
