[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
on_cmd = ['PrevimOpen']

[[plugins]]
repo = 'thinca/vim-showtime'
on_ft = ['markdown']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'syngan/vim-pukiwiki'
on_cmd = ['PukiWiki']
on_ft = ['pukiwiki']

[[plugins]]
repo = 'rhysd/vim-grammarous'
on_cmd = ['GrammarousCheck']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
build = 'git submodule update --init'

